version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  app:
    build: .
    environment:
      DB_HOST: postgres
    ports:
      - 8000:8000
